name: Build and Publish Debian Image

on:
  push:
    branches: [ "main" ]
    paths:
        - configs/Debian/Dockerfile
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  debian-image-docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image & Push to DockerHub
      id: push-docker
      run: |
        docker image build -f configs/Debian/Dockerfile -t docker.io/kbdharun/kasm-dev-debian:latest .
        echo -n ${{ secrets.DOCKER_TOKEN }} | docker login docker.io -u kbdharun --password-stdin
        docker image push "docker.io/kbdharun/kasm-dev-debian:latest"

    - uses: sigstore/cosign-installer@v3.5.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY docker.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

    - name: Attest image
      uses: actions/attest-build-provenance@v1
      id: attest
      with:
        subject-name: index.docker.io/kbdharun/kasm-dev-debian
        subject-digest: ${{ steps.push-docker.outputs.digest }}
        push-to-registry: true

  debian-image-ghcr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image & Push to GHCR
      id: push-ghcr
      run: |
        docker image build -f configs/Debian/Dockerfile -t ghcr.io/kbdharun/kasm-dev-debian:latest .
        echo -n ${{ env.REGISTRY_PASSWORD }} | docker login ghcr.io -u ${{ env.REGISTRY_USER }} --password-stdin
        docker image push "ghcr.io/kbdharun/kasm-dev-debian:latest"
    
    - uses: sigstore/cosign-installer@v3.5.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

    - name: Attest image
      uses: actions/attest-build-provenance@v1
      id: attest
      with:
        subject-name: ghcr.io/kbdharun/kasm-dev-debian
        subject-digest: ${{ steps.push-ghcr.outputs.digest }}
        push-to-registry: true

  debian-image-quay:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image & Push to Quay
      id: push-quay
      run: |
        docker image build -f configs/Debian/Dockerfile -t quay.io/kbdharun/kasm-dev-debian:latest .
        echo -n ${{ secrets.QUAY_TOKEN }} | docker login quay.io -u ${{ secrets.QUAY_USER }} --password-stdin
        docker image push "quay.io/kbdharun/kasm-dev-debian:latest"
    
    - uses: sigstore/cosign-installer@v3.5.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY quay.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
  
    - name: Attest image
      uses: actions/attest-build-provenance@v1
      id: attest
      with:
        subject-name: quay.io/kbdharun/kasm-dev-debian
        subject-digest: ${{ steps.push-quay.outputs.digest }}
        push-to-registry: true
