name: Build and Publish Ubuntu Image

on:
  push:
    branches: [ "main" ]
    paths:
        - configs/Ubuntu-DockerFile
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
    
  ubuntu-image-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Ubuntu-DockerFile -t docker.io/kbdharun/kasm-dev-ubuntu:latest .

    - name: Push To Docker Hub
      run: |
        docker login docker.io -u kbdharun -p ${{ secrets.DOCKER_TOKEN }}
        docker image push "docker.io/kbdharun/kasm-dev-ubuntu:latest"
    
  ubuntu-image-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Ubuntu-DockerFile -t ghcr.io/kbdharun/kasm-dev-ubuntu:latest .

    - name: Push To GHCR
      run: |
        docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
        docker image push "ghcr.io/kbdharun/kasm-dev-ubuntu:latest"
