name: Build and Publish Debian Image

on:
  push:
    branches: [ "main" ]
    paths:
        - configs/Debian/Dockerfile
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  debian-image-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Debian/Dockerfile -t docker.io/kbdharun/kasm-dev-debian:latest .

    - name: Push to DockerHub
      run: |
        echo -n ${{ secrets.DOCKER_TOKEN }} | docker login docker.io -u kbdharun --password-stdin
        docker image push "docker.io/kbdharun/kasm-dev-debian:latest"

    - uses: sigstore/cosign-installer@v3.4.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY docker.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  debian-image-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Debian/Dockerfile -t ghcr.io/kbdharun/kasm-dev-debian:latest .

    - name: Push to GHCR
      run: |
        echo -n ${{ env.REGISTRY_PASSWORD }} | docker login ghcr.io -u ${{ env.REGISTRY_USER }} --password-stdin
        docker image push "ghcr.io/kbdharun/kasm-dev-debian:latest"
    
    - uses: sigstore/cosign-installer@v3.4.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  debian-image-quay:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Debian/Dockerfile -t quay.io/kbdharun/kasm-dev-debian:latest .

    - name: Push to Quay
      run: |
        echo -n ${{ secrets.QUAY_TOKEN }} | docker login quay.io -u ${{ secrets.QUAY_USER }} --password-stdin
        docker image push "quay.io/kbdharun/kasm-dev-debian:latest"
    
    - uses: sigstore/cosign-installer@v3.4.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY quay.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
