name: Build and Publish Fedora Image

on:
  push:
    branches: [ "main" ]
    paths:
        - configs/Fedora/KDE/Dockerfile
        - configs/Fedora/XFCE/Dockerfile
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  fedora-image-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Fedora/XFCE/Dockerfile -t docker.io/kbdharun/kasm-dev-fedora:latest .

    - name: Push to DockerHub
      run: |
        docker login docker.io -u kbdharun -p ${{ secrets.DOCKER_TOKEN }}
        docker image push "docker.io/kbdharun/kasm-dev-fedora:latest"

    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY docker.io/kbdharun/kasm-dev-fedora:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  fedora-image-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Fedora/XFCE/Dockerfile -t ghcr.io/kbdharun/kasm-dev-fedora:latest .

    - name: Push to GHCR
      run: |
        docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
        docker image push "ghcr.io/kbdharun/kasm-dev-fedora:latest"

    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/kbdharun/kasm-dev-fedora:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  fedora-image-quay:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Fedora/XFCE/Dockerfile -t quay.io/kbdharun/kasm-dev-fedora:latest .

    - name: Push to Quay
      run: |
        docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}
        docker image push "quay.io/kbdharun/kasm-dev-fedora:latest"
    
    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY quay.io/kbdharun/kasm-dev-fedora:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  fedora-kde-image-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Fedora/KDE/Dockerfile -t docker.io/kbdharun/kasm-dev-fedora-kde:latest .

    - name: Push to Docker Hub
      run: |
        docker login docker.io -u kbdharun -p ${{ secrets.DOCKER_TOKEN }}
        docker image push "docker.io/kbdharun/kasm-dev-fedora-kde:latest"

    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY docker.io/kbdharun/kasm-dev-fedora-kde:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  fedora-kde-image-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Fedora/KDE/Dockerfile -t ghcr.io/kbdharun/kasm-dev-fedora-kde:latest .

    - name: Push to GHCR
      run: |
        docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
        docker image push "ghcr.io/kbdharun/kasm-dev-fedora-kde:latest"

    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/kbdharun/kasm-dev-fedora-kde:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  fedora-kde-image-quay:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Fedora/KDE/Dockerfile -t quay.io/kbdharun/kasm-dev-fedora-kde:latest .

    - name: Push to Quay
      run: |
        docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}
        docker image push "quay.io/kbdharun/kasm-dev-fedora-kde:latest"
    
    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY quay.io/kbdharun/kasm-dev-fedora-kde:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
