name: Build and Publish Debian Image

on:
  push:
    branches: [ "main" ]
    paths:
        - configs/Debian/Dockerfile
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  debian-image-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Debian/Dockerfile -t docker.io/kbdharun/kasm-dev-debian:latest .

    - name: Push To Docker Hub
      run: |
        docker login docker.io -u kbdharun -p ${{ secrets.DOCKER_TOKEN }}
        docker image push "docker.io/kbdharun/kasm-dev-debian:latest"

    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY docker.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  debian-image-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Debian/Dockerfile -t ghcr.io/kbdharun/kasm-dev-debian:latest .

    - name: Push To GHCR
      run: |
        docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
        docker image push "ghcr.io/kbdharun/kasm-dev-debian:latest"
    
    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  debian-image-quay:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f configs/Debian/Dockerfile -t quay.io/kbdharun/kasm-dev-debian:latest .

    - name: Push To GHCR
      run: |
        docker login quay.io -u ${{ env.QUAY_USER }} -p ${{ env.QUAY_TOKEN }}
        docker image push "quay.io/kbdharun/kasm-dev-debian:latest"
    
    - uses: sigstore/cosign-installer@v3.3.0
    - name: Sign container image
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY quay.io/kbdharun/kasm-dev-debian:latest
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
